config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  resources :wishes, only: [:new, :create, :edit, :update] do
    member { get :lock }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pairing.rb
class Pairing < ApplicationRecord
  belongs_to :recipient, class_name: 'User'
  belongs_to :giver, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  attr_writer :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :first_name, :last_name
  validates :username, presence: true, uniqueness: { case_sensitive: false }, if: :username_required?

  validate :validate_username

  has_many :wishes
  has_many :pairings
  has_one :giver, class_name: 'User'
  has_one :recipient_pairing, -> { where(active: true) }, class_name: 'Pairing', foreign_key: :giver_id
  has_one :recipient, through: :recipient_pairing, class_name: 'User'

  has_one :giver_pairing, -> { where(active: true) }, class_name: 'Pairing', foreign_key: :recipient_id
  has_one :giver, through: :giver_pairing, class_name: 'User'

  before_validation :normalize_login

  def validate_username
    if User.where(email: username).where.not(email: nil).exists?
      errors.add(:username, :invalid)
    end
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end

  def normalize_login
    self.email = nil if email.blank?
    self.username = nil if username.blank?
  end

  def wish_to_fulfill
    wishes.pending.first
  end

  def wish_to_display
    wishes.where('status in (?) and created_at > ?',['pending', 'completed'], Time.now.beginning_of_year).first
  end

  def approved?
    registration_status.eql? 'approved'
  end

  protected

  def email_required?
    username.blank?
  end

  def username_required?
    email.blank?
  end
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :user

  validates_presence_of :description
  validate :one_wish, on: :create

  scope :pending, -> { where(status: 'pending') }
  scope :fulfilled, -> { where(status: 'completed') }
  scope :expired, -> { where(status: 'expired') }

  def one_wish
    return unless Wish.where(user_id: self.user_id, status: 'pending').exists?

    errors.add(:base, :second_pending)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized_error

  def not_authorized_error
    respond_to do |format|
      format.html do
        flash[:error] = t('unauthorized_action')
        redirect_to root_path
      end
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :first_name, :last_name]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @recipient = current_user.recipient
    @wish = @recipient&.wish_to_display
  end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  def new
    @wish = Wish.new
    authorize @wish, :new?
    @current_wish = current_user.wish_to_fulfill || current_user.wish_to_display
  end

  def create
    @wish = current_user.wishes.new(wish_params)
    authorize @wish, :create?
    if @wish.valid? && @wish.save!
      flash[:success] = t('wish.create_success')
      redirect_to new_wish_path
    else
      flash[:error] = @wish.errors.full_messages.join(' ')
      render :new
    end
  end

  def edit
    @wish = Wish.find(params[:id])
    authorize @wish, :edit?
  end

  def update
    @wish = current_user.wishes.find(params[:id])
    authorize @wish, :update?

    if @wish.present? && @wish.status == 'pending' && @wish.update(wish_params)
      flash[:success] = t('wish.update_success')
      redirect_to new_wish_path
    else
      flash[:error] = t('wish.create_failed')
      render :edit
    end
  end


  def lock
    @wish = Wish.find(params[:id])
    if @wish.present? && @wish.status == 'pending'
      @wish.status = 'completed'
      @wish.save!
      flash[:success] = t('wish.locked')
      redirect_to root_path
    else
      flash[:error] = t('wish.already_locked')
      redirect_to root_path
    end
  end

  private

  def wish_params
    params.require(:wish).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then 'alert-info'
    when :success then 'alert-success'
    when :error then 'alert-danger'
    when :alert then 'alert-warning'
    end
  end

  def active_class(link_path)
    current_page?(link_path) ? 'active' : ''
  end
end

app/views/dashboard/index.html.erb
<% if policy(:dashboard).index? %>
  <% if @recipient.present? %>
    <%= render partial: 'dashboard/shared/giftee_card' %>
  <% else %>
    <%= render partial: 'dashboard/shared/empty_giftee_card' %>
  <% end %>
<% end %>

app/views/dashboard/shared/_empty_giftee_card.html.erb
<div class="col-sm-12 col-lg-9 mx-auto mb-5 mb-xl-4 mt-5 mt-sm-0 pt-5">
  <div class="card">
    <div class='image-wrapper'>
      <img class="card-img-top" src="/images/dog.jpg" alt="Card image cap">
      <p class='img_source'>
        Photo by Kostya Naddubov from Pexels
      </p>
    </div>
    <div class="card-body">
      <p class="card-text text-center">Wygląda na to, że nie masz jeszcze osoby do obdarowania.</p>
    </div>
  </div>
</div>

app/views/dashboard/shared/_giftee_card.html.erb
<div class="col-sm-12 col-lg-9 mx-auto mb-5 mb-xl-4 mt-5 mt-sm-0 pt-5">
  <div class="card">
    <div class='image-wrapper'>
      <img class="card-img-top" src="/images/gifts.jpg">
      <p class='img_source'>
        Photo by rawpixel.com from Pexels
      </p>
    </div>
    <div class="card-body">
      <h6 class="card-title text-center text-muted">Obdarowujesz w tym roku:</h6>
      <h5 class="card-title text-center"><%= @recipient.full_name %></h5>
      <h6 class="card-title text-center text-muted">Życzy sobie:</h6>
      <% if @wish.present? %>
        <p class="card-text text-center">
          <%= @wish.description %>
        </p>
        <% if @wish.status == 'pending'%>
          <div class="col-12 text-center">
            <%= link_to t('wish.lock'), lock_wish_path(@wish.id), class: 'btn btn-primary' %>
          </div>
        <% end %>
      <% else %>
        <p class='card-text text-center'>
          Wygląda na to, że jeszcze nie ma tu wymarzonego prezentu.
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SSantaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render partial: 'shared/navbar' %>
      <div>
        <% flash.each do |key, value| %>
          <div class="alert alert-dismissable <%= flash_class(key) %> role="alert" fade in">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= value %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if signed_in? %>
  <nav class='navbar navbar-expand-lg navbar-light bg-light'>
    <a class='navbar-brand'>
      <%= "Sekretny Mikołaj #{current_user.first_name}" %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Strona główna', root_path, class: "nav-item nav-link #{active_class(root_path)}" %>
        <% if policy(:wish).new? %>
          <%= link_to 'Dodaj lub zmień życzenie', new_wish_path, class: "nav-item nav-link #{active_class(new_wish_path)}" %>
        <% end %>
        <%= link_to 'Wyloguj', destroy_user_session_path, method: 'delete', class: 'nav-item nav-link' %>
      </div>
    </div>
  </nav>
<% end %>

app/views/wishes/_form.html.erb
<%= form_for @wish do |form| %>
  <div class='form-group'>
    <%= form.text_area :description, rows: 5, required: true, class: 'form-control', placeholder: t('wish.new_placeholder') %>
  </div>
  <%= form.submit t('save'), class: 'button, btn-primary' %>
<% end %>

app/views/wishes/edit.html.erb
<h2><%= t('wish.input') %> </h2>
<%= render partial: 'form' %>

app/views/wishes/new.html.erb
<h2 class = 'text-center'><%= t('wish.input') %> </h2>
<% if @current_wish.present? %>
  <div class='col-sm-12 col-lg-7 col-xl-7 mx-auto mb-5 mb-xl-4 mt-5 mt-sm-0 pt-5'>
    <div class='card'>
      <div class='image-wrapper'>
        <img class='card-img-top' src='/images/dog.jpg' alt='Card image cap'>
        <p class='img_source'>
          Photo by Kostya Naddubov from Pexels
        </p>
      </div>

      <div class='card-body'>
        <h5 class='card-title text-center'>Twoje tegoroczne życzenie</h5>
        <p class='card-text text-center'>
          <%= @current_wish.description %>
        </p>
        <% if @current_wish.status == 'pending'%>
          <div class='col-12 text-center'>
            <%= link_to 'Zmień życzenie', edit_wish_path(@current_wish.id), class: 'btn btn-primary' %>
          </div>
        <% else %>
          <div class='col-12 text-center'>
            <button type="button" class="btn btn-secondary" data-toggle="popover" data-trigger="focus" title='Za późno!' data-content='Prezent dla Ciebie jest już gotowy. Nie możesz zmienić życzenia.'>Zmień życzenie</button>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= render partial: 'form' %>
  <% end %>
</div>